/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import static java.lang.System.out;

public class App {

    private static final String MY_USER = "sender";
    private static final String MY_PASSWORD = "<PASSWORD>";

    private final String connectionUser;
    private final String connectionPassword;

    public App() {
        connectionUser = MY_USER;
        connectionPassword = MY_PASSWORD;
    }

    public String getConnectionPassword() {
        return this.connectionPassword;
    }

    public String getConnectionUser() {
        return this.connectionUser;
    }

    public static void main(String[] args) {
        App app = new App();
        ConnectionWrapper wrapper = new ConnectionWrapper();
        wrapper.setUser(app.getConnectionUser());
        wrapper.setPassword(app.getConnectionPassword());
        out.println("Connection user is " + wrapper.getUser());
        out.println("Connection password is " + wrapper.getPassword());

        wrapper.prepareConnection("jdbc:mysql://localhost:3306/foo");
        out.println("All done");
    }


    static class ConnectionWrapper {

        private Connection connection;

        private String password;
        private String user;

        public String getPassword() {
            return password;
        }

        public void setPassword(String password) {
            this.password = password;
        }

        public String getUser() {
            return user;
        }

        public void setUser(String user) {
            this.user = user;
        }

        public void prepareConnection(String url) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");

                // NOTE: Passing string constant directly as password argument
                connection = DriverManager.getConnection(url, user, MY_PASSWORD);
            } catch (SQLException | ClassNotFoundException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
